source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'PennyPincher_Example', :exclusive => true do
  pod "PennyPincher", :path => "../"
end

target 'PennyPincher_Tests', :exclusive => true do
  pod "PennyPincher", :path => "../"

  
end
